### ISSUE TITLE
Issues with graphToken after updating binding extensions from beta1 to beta2

### ISSUE THREAD

**Issue by panjkov** [Azure/azure-functions-microsoftgraph-extension#43] opened 2018-03-28 22:48 UTC
Hi,
In the Function app created in the portal using csx
after updating Microsoft Graph extensions from beta1 to beta2 using Kudu as advised by @mattchenderson, (to solve issue 'app not found in directory microsoft.com') I have following issues:
1. On existing Functions with Auth Token or Graph resource binding, I receive error "InvalidOperationException: No value was provided for parameter 'graphToken'."
![image](https://user-images.githubusercontent.com/8397641/38060236-31c25780-32ea-11e8-9ed3-b0aba4c62368.png)
2. If I try to add new Auth Token binding, I keep being informed that "Extension is not installed" and prompted to install extension
![image](https://user-images.githubusercontent.com/8397641/38060331-8b5f089c-32ea-11e8-91eb-2ac4a29b24cb.png)

**Comment by mattchenderson** [comment] 2018-03-28 23:10
Thanks for the additional detail. As discussed in our [Twitter conversation](https://twitter.com/panjkov/status/978560061386711040), the second point is expected. Right now, the templates are built with an assumption about which version to use, and it's doing an equality check. We plan to change this, but for now you'll need to start by creating a function of a different type and then swapping the code and function.json.

We're taking everything forward to beta3, including the templates, as soon as that build is available, which should be soon. That release aligns with the breaking change going into runtime version [2.0.11651](https://github.com/Azure/app-service-announcements/issues/94).

As for the runtime behavior, that's not what I would expect, unless we're dealing with the results of 2.0.11651 (@ConnorMcMahon, thoughts?). That error is what typically happens if the binding fails for some reason. We might be able to get more from the logs in Kudu (`D:\home\LogFiles\Application\Functions\Host` or `D:\home\LogFiles\Application\Functions\Function\<functionName>`). Another piece of information that might be useful is if you could give us the version of the Functions host (Platform features > Function app settings).

**Comment by panjkov** [comment] 2018-03-28 23:33
So, platform version is  2.0.11587.0 (beta)
The host and funcion logs are attached. Hope this helps.
[2018-03-26T23-09-44Z-8178b3b2e8.log](https://github.com/Azure/azure-functions-microsoftgraph-extension/files/1858154/2018-03-26T23-09-44Z-8178b3b2e8.log)
[2018-03-26T22-12-44Z-8178b3b2e8.log](https://github.com/Azure/azure-functions-microsoftgraph-extension/files/1858155/2018-03-26T22-12-44Z-8178b3b2e8.log)

**Comment by ConnorMcMahon** [comment] 2018-03-29 00:06
Looking at those first logs, it looks like the runtime behavior is duplicate of [this issue](https://github.com/Azure/azure-functions-microsoftgraph-extension/issues/37). Make sure you are authenticated via EasyAuth before calling the API, but hopefully soon we will have a better error messages.

**Comment by ConnorMcMahon** [comment] 2018-04-11 18:48
I'm closing this issue, as using beta3 gets around this issue.

**Closed by ConnorMcMahon** 2018-04-11 18:48 UTC
